In [4]:
import numpy as np

In [5]:
l = [1,2,3,4,4]

In [6]:
type(l)

list

using numpy

In [7]:
a = np.array(l)

In [8]:
type(a)

numpy.ndarray

In [9]:
a

array([1, 2, 3, 4, 4])

In [10]:
a1 = np.array([[1,2,3],[4,5,6]])

In [11]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a2 = np.array([[[1,2,3], [4,0.5,6] ]])

In [13]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [14]:
a

array([1, 2, 3, 4, 4])

In [15]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

To check which dimension

In [17]:
a.ndim

1

In [18]:
a1.ndim

2

In [19]:
a2.ndim

3

In [20]:
a3 = np.array([[[1,2,3], [4,0.5,6]], [[1,2,3], [4,.5,6]], [[1,2,3], [4,.5,6]]])

In [21]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [22]:
a3.ndim

3

Asarray function : 

In [23]:
l = [1,2,3,4]

In [28]:
a = np.asarray(l)

In [27]:
m = np.matrix(l)

In [31]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [29]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [30]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

Deepcopy and swallow copy

In [32]:
a

array([1, 2, 3, 4])

In [33]:
a1 = a

In [34]:
a1

array([1, 2, 3, 4])

In [35]:
a

array([1, 2, 3, 4])

In [37]:
a[0]

1

In [38]:
a[0] = 10

In [39]:
a

array([10,  2,  3,  4])

In [40]:
a1

array([10,  2,  3,  4])

In [41]:
a1[3]

4

In [42]:
a1[3] = 50

In [43]:
a1

array([10,  2,  3, 50])

In [44]:
a

array([10,  2,  3, 50])

In [52]:
a2 = np.copy(a) #this is real function to copy the data and is deep copy and above copy function is swallow copy and is affect on copied data also.

In [46]:
a2

array([10,  2,  3, 50])

In [47]:
a2[2]

3

In [48]:
a2[2] = 30

In [49]:
a2

array([10,  2, 30, 50])

In [50]:
a

array([10,  2,  3, 50])

from function

In [55]:
np.fromfunction(lambda i,j : i == j, (3,4))
#this will create 2d data with three rows and four columns where it matches with its index and give data to it

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

random function

In [56]:
np.random.rand(2,3) #this create 2d array

array([[0.51695142, 0.27619042, 0.954323  ],
       [0.37959226, 0.59208648, 0.34925291]])

In [57]:
np.random.rand(2,3,2)#this create 3d array

array([[[0.99689773, 0.06196885],
        [0.75615292, 0.1323266 ],
        [0.06080173, 0.61820996]],

       [[0.99093516, 0.40951235],
        [0.79671951, 0.87529999],
        [0.93132549, 0.18966682]]])

In [59]:
np.random.rand(2,3,2,2)

array([[[[0.0044352 , 0.92120882],
         [0.10499654, 0.2111645 ]],

        [[0.28671146, 0.02214296],
         [0.11233295, 0.80818966]],

        [[0.38513794, 0.70838279],
         [0.69773886, 0.04737677]]],


       [[[0.32045115, 0.4224995 ],
         [0.14555265, 0.19563576]],

        [[0.22828271, 0.86026844],
         [0.07823272, 0.35563609]],

        [[0.36828759, 0.03120845],
         [0.94830921, 0.60805368]]]])

In [60]:
np.random.rand(1,4,4) #this generage 4 rows and 4 columns of 1 arraye

array([[[0.02194553, 0.95384745, 0.17156029, 0.50736564],
        [0.84564004, 0.98561757, 0.29957527, 0.91823122],
        [0.37094457, 0.52780218, 0.84978808, 0.06470144],
        [0.95615698, 0.5159642 , 0.60308152, 0.10471339]]])

In [61]:
np.random.rand(2,4,4) #this generage 4 rows and 4 columns of 2 arraye

array([[[0.20156052, 0.91919933, 0.45969174, 0.91689054],
        [0.8844456 , 0.48805916, 0.87927865, 0.7892822 ],
        [0.31337436, 0.02787643, 0.57534921, 0.29173213],
        [0.37256295, 0.70587097, 0.69891824, 0.75277632]],

       [[0.14360901, 0.38731682, 0.08781946, 0.23222747],
        [0.24150101, 0.72135848, 0.3848286 , 0.17514502],
        [0.92569079, 0.68635549, 0.20320189, 0.53310727],
        [0.31820198, 0.81722795, 0.58343144, 0.62814958]]])

In [62]:
np.random.rand(3,4,4) #this generage 4 rows and 4 columns of 3 arraye

array([[[0.06597137, 0.8366341 , 0.37222096, 0.73259759],
        [0.83150842, 0.75849105, 0.63488051, 0.79505962],
        [0.07044993, 0.4715671 , 0.37088135, 0.1748435 ],
        [0.16776625, 0.79344254, 0.67669641, 0.97646049]],

       [[0.28904435, 0.94891479, 0.50125168, 0.74959942],
        [0.91683233, 0.7380079 , 0.708798  , 0.87263713],
        [0.28506189, 0.82283406, 0.84844252, 0.81453223],
        [0.15509697, 0.68526483, 0.55511109, 0.73179212]],

       [[0.56515964, 0.47469908, 0.06286116, 0.84093019],
        [0.65368579, 0.20674816, 0.20222349, 0.94205881],
        [0.04160703, 0.40380925, 0.17891956, 0.68550064],
        [0.02329875, 0.53542932, 0.82249913, 0.20201694]]])

In [63]:
np.random.randn(3,4,4) #this generage 4 rows and 4 columns of 3 arraye

array([[[-0.1405472 ,  0.24784433, -2.07424888, -0.02153797],
        [ 0.93143203, -1.65351547,  0.29331967,  0.88020552],
        [-2.00625963, -0.30321272,  0.7092661 ,  0.78148563],
        [-0.39764877,  1.76204363, -0.57438939,  0.08416805]],

       [[-0.3204628 ,  1.42159911,  0.12637008,  0.15790459],
        [ 0.84041124,  0.60452944, -1.3453529 ,  0.59142645],
        [-1.66346171, -0.16301355,  1.0354835 , -0.60454095],
        [-1.03149298, -1.22562439,  0.48538723,  0.14364238]],

       [[-2.173249  , -0.13551975,  0.71480063,  1.05642671],
        [-0.446726  ,  0.47130708,  0.53117328,  2.231729  ],
        [ 0.39152135, -1.17743244, -0.50424007,  0.23566644],
        [-0.15176137, -0.29418495,  1.84574502, -0.11396147]]])

In [65]:
np.random.randint(0,10, (4,4)) #this create 4 row 4 column of array and the value in it is between 0 to 10

array([[6, 4, 1, 0],
       [8, 6, 1, 1],
       [4, 0, 0, 7],
       [1, 8, 9, 4]])

In [66]:
np.random.randint(0,10, (4,4,2)) 

array([[[7, 0],
        [7, 8],
        [2, 3],
        [0, 1]],

       [[2, 7],
        [6, 9],
        [9, 2],
        [0, 5]],

       [[3, 4],
        [6, 9],
        [2, 2],
        [6, 9]],

       [[1, 3],
        [3, 9],
        [7, 0],
        [6, 7]]])

In [67]:
d = np.random.randn(3,4)

In [70]:
d

array([[-0.06961685, -0.81137153,  0.53603679, -0.01300694],
       [ 0.97120143,  0.17212356,  0.35062003,  0.39537313],
       [-0.04610735, -0.75705872, -0.54028216, -1.42610499]])

In [69]:
import pandas as pd

In [71]:
pd.DataFrame(d)

0         1         2         3
0 -0.069617 -0.811372  0.536037 -0.013007
1  0.971201  0.172124  0.350620  0.395373
2 -0.046107 -0.757059 -0.540282 -1.426105

In [72]:
d1 = np.random.randint(0,10, (4,4,2)) 

In [ ]:
pd.DataFrame(d1) #Panda Datafram cant convert 3d data in dataframe

In [86]:
d1.reshape(16,2) #to convert 3d to 2d use this function and give the paramert equal to the number of data is available in 3d and in that format (n,n) where n*n = total 3d data.

array([[5, 8],
       [0, 7],
       [5, 5],
       [4, 6],
       [2, 7],
       [3, 5],
       [9, 2],
       [8, 1],
       [7, 1],
       [2, 9],
       [8, 0],
       [9, 7],
       [4, 9],
       [2, 9],
       [2, 7],
       [1, 8]])

In [87]:
d1.reshape(8,4)

array([[5, 8, 0, 7],
       [5, 5, 4, 6],
       [2, 7, 3, 5],
       [9, 2, 8, 1],
       [7, 1, 2, 9],
       [8, 0, 9, 7],
       [4, 9, 2, 9],
       [2, 7, 1, 8]])

In [ ]:
d1.reshape(10,4) #this throw error becuase 10*4 is not equal to the total unumber of data available in 3d dimenstion

In [92]:
d1.reshape(8,-1) #this will automatically convert 3d to 2d becuase of -value in it means 8,-1 = 8 row and -1 equal to system automatic create it.

array([[5, 8, 0, 7],
       [5, 5, 4, 6],
       [2, 7, 3, 5],
       [9, 2, 8, 1],
       [7, 1, 2, 9],
       [8, 0, 9, 7],
       [4, 9, 2, 9],
       [2, 7, 1, 8]])

In [96]:
pd.DataFrame(d1.reshape(4,-1))

0  1  2  3  4  5  6  7
0  5  8  0  7  5  5  4  6
1  2  7  3  5  9  2  8  1
2  7  1  2  9  8  0  9  7
3  4  9  2  9  2  7  1  8