In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

creting array floating point number

arrange fununction

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [9]:
np.arange(5,-4, -1) #it means start from 5 go till -4 and get jump of -1

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [14]:
np.arange(5,-4, -0.5) #it means start from 5 go till -4 and get jump of -.5

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

linespace function

In [17]:
np.linspace(1,5, 20) #this generates 20 data form 1 to 5 including floating point number or it divided 1 to 5 in 20 parts

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [21]:
list(np.linspace(1,5, 20, retstep=True)) #here retstep also show what jumpsize between it takes in the output at last

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

logspace function

In [27]:
np.logspace(1,5,10) #this generates 20 data form 1 to 5 with log of the value in 10 part with base 10 by default

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [34]:
np.logspace(1,5,10, base=4)
#BASE MEAANS STEP BETWEEN THE ELEMENT
#"The base of the log space. The step size between the elements in
#``ln(samples) / ln(base)`` (or ``log_base(samples)``)
# is uniform Default is 10.0."

array([   4.        ,    7.4069977 ,   13.71590373,   25.39841683,
         47.03150375,   87.09056001,  161.26989439,  298.63143413,
        552.99058631, 1024.        ])

zEROS FUNCTION

In [36]:
np.zeros(5) #it will generate an array of 5 zeros int it

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((3,5)) # here it will generate an zero value of array 2 dimenstion 3 rows and 5 columnss

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.zeros((3,5,2)) # here it will generate an zero value of array 3 dimenstion 5 rows and 2 columnss in 3 layer/3d

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

ones function

In [42]:
np.ones(5) #it create an array of 5 element and 1 value in it as the function name says

array([1., 1., 1., 1., 1.])

In [47]:
np.ones((3,4,2)) #it create a 3d arraye of 2 rows and 4 columns and 1 value in it

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [51]:
np.ones((3,4,2)) * 5 #it create a 3d arraye of 2 rows and 4 columns and 1 value in it and multiply by 5 every element

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

Empty funtion

In [54]:
np.empty((2,3)) #it create an empty array

array([[4.66671504e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

eye function

In [57]:
np.eye(4) #it create an 2d arraye of  4 row and 4 columns and what value in it

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
a = np.eye(4)

shape funtion

In [60]:
a.shape #it give the dimenstion of "a" data or any given data

(4, 4)

size function

In [62]:
a.size #it give the size of the of element availabel in the aarray

16

ndim function

In [64]:
a.ndim #it give the dimension of array

2

Slicing indexing opration

In [66]:
a1 =  np.random.randn(3,4)

In [71]:
import pandas as pd
pd.DataFrame(a1)

0         1         2         3
0  0.212569  0.553463  0.540740 -1.675500
1 -1.405000  0.897096 -0.574916 -0.123196
2  0.791178  0.584029 -0.201837  0.749239

In [67]:
a1

array([[ 0.21256854,  0.55346258,  0.5407404 , -1.67549967],
       [-1.40499993,  0.89709597, -0.57491608, -0.12319625],
       [ 0.7911776 ,  0.58402925, -0.20183743,  0.74923906]])

In [72]:
a1[1,1]

0.8970959728383008

In [73]:
a1[1][1]

0.8970959728383008

In [75]:
a1[0:2, 0:2]

array([[ 0.21256854,  0.55346258],
       [-1.40499993,  0.89709597]])

In [76]:
a1[[0,1], 0:2]

array([[ 0.21256854,  0.55346258],
       [-1.40499993,  0.89709597]])

In [81]:
a1[[0,1],0:2]

array([[ 0.21256854,  0.55346258],
       [-1.40499993,  0.89709597]])

In [82]:
a1

array([[ 0.21256854,  0.55346258,  0.5407404 , -1.67549967],
       [-1.40499993,  0.89709597, -0.57491608, -0.12319625],
       [ 0.7911776 ,  0.58402925, -0.20183743,  0.74923906]])

In [89]:
a1[[1,2]]

array([[-1.40499993,  0.89709597, -0.57491608, -0.12319625],
       [ 0.7911776 ,  0.58402925, -0.20183743,  0.74923906]])

In [90]:
a1[[1,2],3]

array([-0.12319625,  0.74923906])

Metrix Multiplication

In [94]:
m1 = np.random.randint(1,3,(3,3)) #it creant a 2d array of 3row and 3 column and value in it is between 1 to 3 of random number

In [96]:
m1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [97]:
m2 = np.random.randint(2,4,(3,3))

In [98]:
m2

array([[2, 3, 3],
       [2, 3, 2],
       [3, 3, 2]])

In [100]:
m1*m2 #it multiply the value of each number with the same index and create a new metrices of same dimension

array([[2, 3, 6],
       [4, 6, 2],
       [3, 3, 2]])

In [102]:
m1@m2 #metix multiplycation done by "@" between two metrices

array([[10, 12,  9],
       [11, 15, 12],
       [ 7,  9,  7]])

In [103]:
m1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [104]:
m2

array([[2, 3, 3],
       [2, 3, 2],
       [3, 3, 2]])

pow function : to generate power of each element in the array

In [105]:
m1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [106]:
pow(m1,2)

array([[1, 1, 4],
       [4, 4, 1],
       [1, 1, 1]])

sqrt() function

In [108]:
np.sqrt(m1) #it will find the square root of each of the element in the arraye

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [111]:
np.log10(m1)#it will find the log (logarathmic) of each of the element in the arraye with base 10

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [112]:
np.exp(m1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [114]:
m1**2 #it square all the element of aray

array([[1, 1, 4],
       [4, 4, 1],
       [1, 1, 1]])